language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: devcon5
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

jobs:
  include:
    - script: mvn clean package
    - if: type = pull_request
      script: mvn sonar:sonar

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
